# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - FosterPet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        env:
          SPRING_DATA_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          AZURE_BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          AZURE_COMMUNICATION_CHAT_ENDPOINT: ${{ secrets.AZURE_COMMUNICATION_CHAT_ENDPOINT }}
          AZURE_COMMUNICATION_CHAT_ACCESS_KEY: ${{ secrets.AZURE_COMMUNICATION_CHAT_ACCESS_KEY }}
          AZURE_COMMUNICATION_CHAT_ADMIN_USER_ID: ${{ secrets.AZURE_COMMUNICATION_CHAT_ADMIN_USER_ID }}
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FosterPet'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6218B703B194C2990123035BA8D52AC }}
          package: '*.jar'
